
- name: "Android | SDK | Validate 'android_sdk' variable"
  ansible.utils.validate:
    data: "{{ android_sdk }}"
    criteria: "{{ lookup('file', 'assertions/criteria/android-sdk-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost

- name: "Android | SDK | set 'android_sdk_home' variable"
  ansible.builtin.set_fact:
    android_sdk_home: "{{  android_sdk.environment.variables.sdk_home.path | default(android_sdk_home) }}"

- name: "Android | SDK | Configure sdk"
  ansible.builtin.import_tasks: configure.yml
  when:
    - android_sdk.remove is undefined or not android_sdk.remove

- name: "Android | SDK | Remove sdk"
  ansible.builtin.import_tasks: remove.yml
  when:
    - android_sdk.remove is defined and android_sdk.remove
