- name: "Android | SDK | Remove android.sh profile"
  ansible.builtin.file: 
    path: /etc/profile.d/android.sh
    state: absent

- name: "Android | SDK | Remove 'adb' binary from path"
  ansible.builtin.file:
    path: "{{ android_sdk_bin }}/adb"
    state: absent

- name: "Android | SDK | Remove 'sdkmanager' binary from path"
  ansible.builtin.file:
    path: "{{ android_sdk_bin }}/sdkmanager"
    state: absent

- name: "Android | SDK | Remove udev rules"
  ansible.builtin.file:
    path: /lib/udev/rules.d/51-android.rules
    state: absent

- name: "Android | SDK | Ensure 'android_sdk_home' directory"
  ansible.builtin.file:
    path: "{{ android_sdk_home }}"
    state: absent
